[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.startCommand]
command = "npm start"

[build.environment]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 